import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'

export default function Home() {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <div className='bg-mainColor w-full h-screen'>
          <nav className='p-4'>
            <span className='text-whiteAlternate hover:text-blueAlternate1 text-4xl font-montserrat font-bold float-left transition duration-300'>VIT Vellore Events</span>
            <ul className='text-whiteAlternate font-montserrat float-left text-2xl m-1.5 ml-6'>
              <li className='float-left ml-3 mr-3'><a href='/clubs/defaultClub' className='hover:text-blueAlternate1 transition duration-300'>Clubs</a></li>
              <li className='float-left ml-3 mr-3'><a href='/events/defaultEvent' className='hover:text-blueAlternate1 transition duration-300'>Events</a></li>
            </ul>
            <hr className='text-center clear-both text-mainAccent '/>
          </nav>
        </div>
      </main>
    </div>
  )
}
